### ISSUE TITLE
Add Documentation Generation docs

### ISSUE THREAD

**Issue by ChloePlanet** [anz-bank/sysl-website#31]
## Description
- [ ] https://github.com/anz-bank/sysl-website/blob/master/docs/gen-docs.md

Reference: https://github.com/anz-bank/sysl-catalog

## Documentation Structure
Feature documentation doesn't have template, any structure which is clear and comprehensive is fine.

Command documentation reference: 
- https://vibrant-neumann-307d85.netlify.app/docs/cmd-import
- https://vibrant-neumann-307d85.netlify.app/docs/cmd-info/

**Comment by cuminandpaprika** [comment]
Closed in
