### ISSUE TITLE
Add commands import and export documentation

### ISSUE THREAD

**Issue by ChloePlanet** [anz-bank/sysl-website#6]
### Description
https://github.com/anz-bank/sysl-website/blob/master/docs/cmd-import.md
https://github.com/anz-bank/sysl-website/blob/master/docs/cmd-export.md
### Estimated Time
2 days

**Comment by ericzhang6222** [comment]
Reference https://golang.org/cmd/go/

**Comment by ericzhang6222** [comment]
Closed by https://github.com/anz-bank/sysl-website/pull/17
